/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/internal/competitors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Competitors */
    get: operations["competitors_api_internal_competitors_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/console/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_internal_console_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/console/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Clear the cookie.
     *
     *     Deliberately unguarded: signing out must work even from a session that has
     *     already expired, and refusing to clear a cookie helps nobody. The attribute
     *     set here must match the login cookie or the browser will keep the old one.
     */
    post: operations["logout_api_internal_console_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/console/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Me
     * @description Who am I. The SPA calls this on load to decide login vs console.
     */
    get: operations["me_api_internal_console_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/geocoding/funnel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Geocoding Funnel */
    get: operations["geocoding_funnel_api_internal_geocoding_funnel_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/geocoding/queue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Geocoding Queue
     * @description Open jobs, busiest first.
     */
    get: operations["geocoding_queue_api_internal_geocoding_queue_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/geocoding/queue/{queue_id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reject Job
     * @description A human looked and could not place it. Nothing is written to the cache.
     */
    post: operations["reject_job_api_internal_geocoding_queue__queue_id__reject_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/geocoding/queue/{queue_id}/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resolve Job
     * @description Place the point, and write it back into the cache so it stays placed.
     */
    post: operations["resolve_job_api_internal_geocoding_queue__queue_id__resolve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Healthz
     * @description Liveness only. Does not touch the database.
     */
    get: operations["healthz_api_internal_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/lookup/coverage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lookup Coverage
     * @description Per state: what evidence exists, and the tier that follows from it.
     *
     *     ⚠️ Every evidence flag below is currently derived from a table that either
     *     does not exist yet or is empty, so the honest answer is Tier 3 everywhere.
     *     That is the correct answer and it is stated rather than worked around - the
     *     alternative, hardcoding "Kerala and Tamil Nadu are Tier 1", would make the
     *     console agree with the plan instead of with the database.
     */
    get: operations["lookup_coverage_api_internal_lookup_coverage_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/lookup/point": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lookup Point
     * @description Resolve one coordinate and show the working.
     *
     *     The bounds are not decoration: a transposed lat/lng is the commonest way a
     *     hand-entered point goes wrong, and (76.2, 9.9) is a coordinate in Kazakhstan
     *     that would otherwise be rejected 5 km later with no explanation of why.
     */
    get: operations["lookup_point_api_internal_lookup_point_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/lookup/tables": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lookup Tables
     * @description Row counts for every table that carries meaning, with what it is for.
     *
     *     One round trip rather than fifteen: the counts are unioned into a single
     *     statement, which matters when the database is a hop away.
     */
    get: operations["lookup_tables_api_internal_lookup_tables_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/poller/alive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Poller Alive
     * @description Unauthenticated liveness for an external uptime monitor.
     *
     *     Returns 503 when nothing is being recorded, so a generic "is this URL
     *     healthy" checker becomes a second alarm that does not depend on our own
     *     logging, our own alerting, or our own process being alive to send it.
     *
     *     Deliberately says nothing else. Which networks we poll, and what they last
     *     told us, is console data and lives behind the guard.
     */
    get: operations["poller_alive_api_internal_poller_alive_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/poller/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Poller Health Endpoint */
    get: operations["poller_health_endpoint_api_internal_poller_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Progress */
    get: operations["progress_api_internal_progress_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readyz
     * @description Readiness: database reachable and PostGIS actually installed.
     *
     *     PostGIS is checked explicitly because every spatial query in Part 1
     *     silently becomes an error without it, and the failure surfaces far from
     *     the cause.
     */
    get: operations["readyz_api_internal_readyz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cpo Sources Endpoint
     * @description The CPO/source registry with governance + measured status side by side.
     *
     *     Feeds the console CPO panel: which networks we scrape, whether each is
     *     authorised and configured, and what our own poller last saw from it -
     *     uptime we measured, not uptime the operator claimed.
     */
    get: operations["cpo_sources_endpoint_api_internal_sources_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/vahan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Vahan */
    get: operations["vahan_api_internal_vahan_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ping */
    get: operations["ping_api_v1_ping_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AliveOut */
    AliveOut: {
      /** Alive */
      alive: boolean;
      /** Never Run */
      never_run: boolean;
    };
    /** ClassRow */
    ClassRow: {
      /** Ev Total */
      ev_total: number;
      /** Group */
      group: string;
    };
    /** CompetitorsOut */
    CompetitorsOut: {
      /** By State */
      by_state: components["schemas"]["StateRow"][];
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Fetched From */
      fetched_from: string[];
      /** Top Operators */
      top_operators: components["schemas"]["OperatorRow"][];
      /** Total */
      total: number;
      /** Unplaced */
      unplaced: number;
    };
    /** CoverageOut */
    CoverageOut: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Note */
      note: string;
      /** Rule */
      rule: string;
      /** States */
      states: components["schemas"]["StateCoverageOut"][];
    };
    /**
     * CpoSourceOut
     * @description One scraped/roamed CPO source, for the console CPO panel (PLAN C.4).
     */
    CpoSourceOut: {
      /** Authorised */
      authorised: boolean;
      /** Blocking Reason */
      blocking_reason: string | null;
      /** Configured */
      configured: boolean;
      /** Connectors Last Run */
      connectors_last_run: number;
      /** Events Last Run */
      events_last_run: number;
      /** Kind */
      kind: string;
      /** Last Error */
      last_error: string | null;
      /** Last Success At */
      last_success_at: string | null;
      /** Pollable */
      pollable: boolean;
      /** Rate Limit Per Minute */
      rate_limit_per_minute: number | null;
      /** Source */
      source: string;
      /** Stations Last Run */
      stations_last_run: number;
      /** Terms Note */
      terms_note: string | null;
      /** Terms Url */
      terms_url: string | null;
    };
    /** CpoSourcesOut */
    CpoSourcesOut: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Sources */
      sources: components["schemas"]["CpoSourceOut"][];
    };
    /** DistrictVahanRow */
    DistrictVahanRow: {
      /** District */
      district: string;
      /** Ev Total */
      ev_total: number;
      /** Growth Pct */
      growth_pct: number | null;
      /** Lgd District Code */
      lgd_district_code: number | null;
      /** State */
      state: string;
    };
    /**
     * FieldSource
     * @description Where one field on the answer physically came from.
     */
    FieldSource: {
      /** Field */
      field: string;
      /** Note */
      note: string;
      /** Source */
      source: string;
      /** Value */
      value: string;
    };
    /** FunnelOut */
    FunnelOut: {
      /**
       * Billing Month
       * Format: date
       */
      billing_month: string;
      /** Cached Addresses */
      cached_addresses: number;
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Free Share */
      free_share: number | null;
      /** Levels */
      levels: components["schemas"]["LevelOut"][];
      /** Queue Open */
      queue_open: number;
      /** Queue Rejected */
      queue_rejected: number;
      /** Queue Resolved */
      queue_resolved: number;
      /** Resolved */
      resolved: number;
      /** Spend */
      spend: components["schemas"]["SpendOut"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
    };
    /**
     * InputOut
     * @description One external thing only a human can supply: a key, an endpoint, a file.
     *
     *     The status is read from live settings at request time, so pasting a line
     *     into ``.env`` and restarting the API flips the row on its own - the page
     *     can never claim a key exists that the process cannot see.
     */
    InputOut: {
      /** Detail */
      detail: string;
      /** Env Vars */
      env_vars: string[];
      /** How To Get */
      how_to_get: string;
      /** Kind */
      kind: string;
      /** Name */
      name: string;
      /** Needed For */
      needed_for: string;
      status: components["schemas"]["InputStatus"];
    };
    /**
     * InputStatus
     * @enum {string}
     */
    InputStatus: "configured" | "missing" | "attention" | "later";
    /**
     * LayerOut
     * @description Provenance of the map data itself - PLAN C.5's data-vintage row.
     */
    LayerOut: {
      /**
       * Downloaded At
       * Format: date-time
       */
      downloaded_at: string;
      /** Feature Count */
      feature_count: number;
      /** Licence */
      licence: string;
      /** Name */
      name: string;
      /** Source Url */
      source_url: string;
    };
    /**
     * LevelOut
     * @description One cascade level's share of the cache.
     */
    LevelOut: {
      /** Resolved */
      resolved: number;
      /** Source */
      source: string;
      /** Unresolved */
      unresolved: number;
    };
    /** LoginIn */
    LoginIn: {
      /** Password */
      password: string;
    };
    /** MilestoneOut */
    MilestoneOut: {
      /** Evidence */
      evidence: string;
      /** Order */
      order: number;
      /** Part */
      part: string;
      status: components["schemas"]["Status"];
      /** Title */
      title: string;
      /** To Close */
      to_close?: string | null;
      /** What */
      what: string;
    };
    /** NeighbourOut */
    NeighbourOut: {
      /** Distance M */
      distance_m: number;
      /** Lgd District Code */
      lgd_district_code: number;
      /** Name */
      name: string;
      /** State Name */
      state_name: string;
    };
    /** Operator */
    Operator: {
      /** Operator */
      operator: string;
    };
    /** OperatorRow */
    OperatorRow: {
      /** Dc Fast */
      dc_fast: number;
      /** Operator */
      operator: string;
      /** Stations */
      stations: number;
    };
    /** PointOut */
    PointOut: {
      /** Boundary Ambiguous */
      boundary_ambiguous: boolean;
      /** Confidence */
      confidence: string;
      /** Distance M */
      distance_m: number;
      /** District */
      district: string | null;
      /** Fields */
      fields: components["schemas"]["FieldSource"][];
      /** Lat */
      lat: number;
      /** Layers */
      layers: components["schemas"]["LayerOut"][];
      /** Lgd District Code */
      lgd_district_code: number | null;
      /** Lgd State Code */
      lgd_state_code: number | null;
      /** Lng */
      lng: number;
      /** Method */
      method: string;
      neighbour: components["schemas"]["NeighbourOut"] | null;
      /** Overridden District */
      overridden_district: string | null;
      /** Pin Conflict */
      pin_conflict: boolean;
      /** Pincode At Point */
      pincode_at_point: string[];
      /** Reasons */
      reasons: string[];
      /** Resolved */
      resolved: boolean;
      /** State Name */
      state_name: string | null;
      /** Steps */
      steps: components["schemas"]["Step"][];
      /** Supplied Pincode */
      supplied_pincode: string | null;
    };
    /** PollerHealthOut */
    PollerHealthOut: {
      /** Alive */
      alive: boolean;
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Never Run */
      never_run: boolean;
      /** Sources */
      sources: components["schemas"]["SourceHealthOut"][];
      /** Stale Sources */
      stale_sources: string[];
      /** Threshold Minutes */
      threshold_minutes: number;
    };
    /** ProgressOut */
    ProgressOut: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Inputs */
      inputs: components["schemas"]["InputOut"][];
      /** Milestones */
      milestones: components["schemas"]["MilestoneOut"][];
      /** Summary */
      summary: string;
    };
    /** QueueItemOut */
    QueueItemOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Hits */
      hits: number;
      /** Id */
      id: number;
      /** Lat */
      lat: number | null;
      /** Lng */
      lng: number | null;
      /** Normalised Input */
      normalised_input: string;
      /** Pincode */
      pincode: string | null;
      /** Raw Input */
      raw_input: string;
      /** Reason */
      reason: string | null;
      /** Status */
      status: string;
    };
    /** QueueOut */
    QueueOut: {
      /** Items */
      items: components["schemas"]["QueueItemOut"][];
      /** Open Count */
      open_count: number;
    };
    /** Readiness */
    Readiness: {
      /** Database */
      database: string;
      /** Env */
      env: string;
      /** Paid Providers Enabled */
      paid_providers_enabled: string[];
      /** Postgis */
      postgis: string;
    };
    /** RejectIn */
    RejectIn: {
      /** Note */
      note?: string | null;
    };
    /** ResolveIn */
    ResolveIn: {
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
      /** Note */
      note?: string | null;
    };
    /** SourceHealthOut */
    SourceHealthOut: {
      /** Blocking Reason */
      blocking_reason: string | null;
      /** Connectors Last Run */
      connectors_last_run: number;
      /** Events Last Run */
      events_last_run: number;
      /** Last Error */
      last_error: string | null;
      /** Last Success At */
      last_success_at: string | null;
      /** Pollable */
      pollable: boolean;
      /** Raw Pages Last Run */
      raw_pages_last_run: number;
      /** Silent For Seconds */
      silent_for_seconds: number | null;
      /** Source */
      source: string;
      /** Stale */
      stale: boolean;
    };
    /** SpendOut */
    SpendOut: {
      /** Calls */
      calls: number;
      /** Cost Paise */
      cost_paise: number;
      /** Provider */
      provider: string;
    };
    /** StateCoverageOut */
    StateCoverageOut: {
      /** Districts */
      districts: number;
      /** Focus */
      focus: boolean;
      /** Has Competitor Poll */
      has_competitor_poll: boolean;
      /** Has Osm Road Quality */
      has_osm_road_quality: boolean;
      /** Has Tariff Data */
      has_tariff_data: boolean;
      /** Has Vahan Data */
      has_vahan_data: boolean;
      /** Lgd State Code */
      lgd_state_code: number;
      /** State */
      state: string;
      /**
       * Tier
       * @description 1 = full report · 2 = tariff audit only · 3 = waitlist
       */
      tier: number;
      /** Why */
      why: string;
    };
    /** StateRow */
    StateRow: {
      /** Lgd State Code */
      lgd_state_code: number;
      /** State */
      state: string;
      /** Stations */
      stations: number;
    };
    /** StateVahanRow */
    StateVahanRow: {
      /** Districts */
      districts: number;
      /** Ev Total */
      ev_total: number;
      /** Growth Pct */
      growth_pct: number | null;
      /** Lgd State Code */
      lgd_state_code: number;
      /** State */
      state: string;
    };
    /**
     * Status
     * @enum {string}
     */
    Status: "done" | "code_done" | "partial" | "next" | "parked" | "not_started";
    /**
     * Step
     * @description One question the resolver asked, and where it went for the answer.
     */
    Step: {
      /** Answer */
      answer: string;
      /**
       * Decisive
       * @default false
       */
      decisive: boolean;
      /** Looked In */
      looked_in: string;
      /** N */
      n: number;
      /** Question */
      question: string;
      /** Using */
      using: string;
    };
    /** TableOut */
    TableOut: {
      /** Empty Means */
      empty_means?: string | null;
      /** Filled By */
      filled_by: string;
      /** Group */
      group: string;
      /** Rows */
      rows: number;
      /** Table */
      table: string;
      /** What */
      what: string;
    };
    /** TablesOut */
    TablesOut: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Extension Tables */
      extension_tables: string[];
      /** Tables */
      tables: components["schemas"]["TableOut"][];
      /** Undocumented */
      undocumented: string[];
    };
    /** VahanOut */
    VahanOut: {
      /** By Class */
      by_class: components["schemas"]["ClassRow"][];
      /** By State */
      by_state: components["schemas"]["StateVahanRow"][];
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Display Period */
      display_period: string | null;
      /** Periods */
      periods: string[];
      /** Snapshot Date */
      snapshot_date: string | null;
      /** Top Districts */
      top_districts: components["schemas"]["DistrictVahanRow"][];
      /** Total Rows */
      total_rows: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  competitors_api_internal_competitors_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompetitorsOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_internal_console_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Operator"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_internal_console_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_api_internal_console_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Operator"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  geocoding_funnel_api_internal_geocoding_funnel_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FunnelOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  geocoding_queue_api_internal_geocoding_queue_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueueOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reject_job_api_internal_geocoding_queue__queue_id__reject_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        queue_id: number;
      };
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RejectIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueueItemOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  resolve_job_api_internal_geocoding_queue__queue_id__resolve_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        queue_id: number;
      };
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolveIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueueItemOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  healthz_api_internal_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  lookup_coverage_api_internal_lookup_coverage_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoverageOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  lookup_point_api_internal_lookup_point_get: {
    parameters: {
      query: {
        /** @description India's bounding box, roughly */
        lat: number;
        lng: number;
        pincode?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PointOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  lookup_tables_api_internal_lookup_tables_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TablesOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  poller_alive_api_internal_poller_alive_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AliveOut"];
        };
      };
    };
  };
  poller_health_endpoint_api_internal_poller_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PollerHealthOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  progress_api_internal_progress_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgressOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  readyz_api_internal_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Readiness"];
        };
      };
    };
  };
  cpo_sources_endpoint_api_internal_sources_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CpoSourcesOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  vahan_api_internal_vahan_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VahanOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  ping_api_v1_ping_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
