/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/internal/assess": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Assess */
    post: operations["assess_api_internal_assess_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/competitors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Competitors */
    get: operations["competitors_api_internal_competitors_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/console/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_internal_console_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/console/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Clear the cookie.
     *
     *     Deliberately unguarded: signing out must work even from a session that has
     *     already expired, and refusing to clear a cookie helps nobody. The attribute
     *     set here must match the login cookie or the browser will keep the old one.
     */
    post: operations["logout_api_internal_console_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/console/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Me
     * @description Who am I. The SPA calls this on load to decide login vs console.
     */
    get: operations["me_api_internal_console_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/features": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Features
     * @description Which deferred features are switched on, so the SPA can hide the rest.
     */
    get: operations["features_api_internal_features_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/geocoding/funnel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Geocoding Funnel */
    get: operations["geocoding_funnel_api_internal_geocoding_funnel_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/geocoding/queue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Geocoding Queue
     * @description Open jobs, busiest first.
     */
    get: operations["geocoding_queue_api_internal_geocoding_queue_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/geocoding/queue/{queue_id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reject Job
     * @description A human looked and could not place it. Nothing is written to the cache.
     */
    post: operations["reject_job_api_internal_geocoding_queue__queue_id__reject_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/geocoding/queue/{queue_id}/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resolve Job
     * @description Place the point, and write it back into the cache so it stays placed.
     */
    post: operations["resolve_job_api_internal_geocoding_queue__queue_id__resolve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Healthz
     * @description Liveness only. Does not touch the database.
     */
    get: operations["healthz_api_internal_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/lookup/coverage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lookup Coverage
     * @description Per state: what evidence exists, and the tier that follows from it.
     *
     *     ⚠️ Every evidence flag below is currently derived from a table that either
     *     does not exist yet or is empty, so the honest answer is Tier 3 everywhere.
     *     That is the correct answer and it is stated rather than worked around - the
     *     alternative, hardcoding "Kerala and Tamil Nadu are Tier 1", would make the
     *     console agree with the plan instead of with the database.
     */
    get: operations["lookup_coverage_api_internal_lookup_coverage_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/lookup/point": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lookup Point
     * @description Resolve one coordinate and show the working.
     *
     *     The bounds are not decoration: a transposed lat/lng is the commonest way a
     *     hand-entered point goes wrong, and (76.2, 9.9) is a coordinate in Kazakhstan
     *     that would otherwise be rejected 5 km later with no explanation of why.
     */
    get: operations["lookup_point_api_internal_lookup_point_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/lookup/tables": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lookup Tables
     * @description Row counts for every table that carries meaning, with what it is for.
     *
     *     One round trip rather than fifteen: the counts are unioned into a single
     *     statement, which matters when the database is a hop away.
     */
    get: operations["lookup_tables_api_internal_lookup_tables_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/network/facets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Facets */
    get: operations["facets_api_internal_network_facets_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/network/stations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Stations */
    get: operations["list_stations_api_internal_network_stations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/network/stations/{station_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Station Detail */
    get: operations["station_detail_api_internal_network_stations__station_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/owner/bill-images": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Bill Image */
    post: operations["upload_bill_image_api_internal_owner_bill_images_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/owner/bill-images/{image_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Bill Image */
    get: operations["bill_image_api_internal_owner_bill_images__image_id__get"];
    put?: never;
    post?: never;
    /**
     * Remove Bill Image
     * @description Delete one bill image. The figures the owner confirmed from it stay.
     */
    delete: operations["remove_bill_image_api_internal_owner_bill_images__image_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/owner/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_internal_owner_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/owner/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_internal_owner_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/owner/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_internal_owner_me_get"];
    put?: never;
    post?: never;
    /**
     * Erase Me
     * @description Erase the account and everything it holds: phone number, stations, bills, images.
     */
    delete: operations["erase_me_api_internal_owner_me_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/owner/onboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Onboard */
    post: operations["onboard_api_internal_owner_onboard_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/owner/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signup */
    post: operations["signup_api_internal_owner_signup_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/owner/stations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Stations */
    get: operations["my_stations_api_internal_owner_stations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/owner/stations/{station_id}/area": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Owner Area */
    get: operations["owner_area_api_internal_owner_stations__station_id__area_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/owner/stations/{station_id}/bills": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Save Bill */
    post: operations["save_bill_api_internal_owner_stations__station_id__bills_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/owner/stations/{station_id}/grid": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Owner Grid */
    get: operations["owner_grid_api_internal_owner_stations__station_id__grid_get"];
    put?: never;
    /** Owner Grid Save */
    post: operations["owner_grid_save_api_internal_owner_stations__station_id__grid_post"];
    /** Owner Grid Withdraw */
    delete: operations["owner_grid_withdraw_api_internal_owner_stations__station_id__grid_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/owner/stations/{station_id}/home": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Home */
    get: operations["home_api_internal_owner_stations__station_id__home_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/owner/stations/{station_id}/outages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Owner Outage Save */
    post: operations["owner_outage_save_api_internal_owner_stations__station_id__outages_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/poller/alive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Poller Alive
     * @description Unauthenticated liveness for an external uptime monitor.
     *
     *     Returns 503 when nothing is being recorded, so a generic "is this URL
     *     healthy" checker becomes a second alarm that does not depend on our own
     *     logging, our own alerting, or our own process being alive to send it.
     *
     *     Deliberately says nothing else. Which networks we poll, and what they last
     *     told us, is console data and lives behind the guard.
     */
    get: operations["poller_alive_api_internal_poller_alive_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/poller/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Poller Health Endpoint */
    get: operations["poller_health_endpoint_api_internal_poller_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Progress */
    get: operations["progress_api_internal_progress_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readyz
     * @description Readiness: database reachable and PostGIS actually installed.
     *
     *     PostGIS is checked explicitly because every spatial query in Part 1
     *     silently becomes an error without it, and the failure surfaces far from
     *     the cause.
     */
    get: operations["readyz_api_internal_readyz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/reports/{report_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Report */
    get: operations["report_api_internal_reports__report_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cpo Sources Endpoint
     * @description The CPO/source registry with governance + measured status side by side.
     *
     *     Feeds the console CPO panel: which networks we scrape, whether each is
     *     authorised and configured, and what our own poller last saw from it -
     *     uptime we measured, not uptime the operator claimed.
     */
    get: operations["cpo_sources_endpoint_api_internal_sources_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/vahan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Vahan */
    get: operations["vahan_api_internal_vahan_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ping */
    get: operations["ping_api_v1_ping_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AliveOut */
    AliveOut: {
      /** Alive */
      alive: boolean;
      /** Never Run */
      never_run: boolean;
    };
    /** AnchorNote */
    AnchorNote: {
      /** Irr Pct */
      irr_pct: number;
      /** Kwh Year */
      kwh_year: number;
      /** Npv Paise */
      npv_paise: number;
    };
    /** AreaItem */
    AreaItem: {
      /** Key */
      key: string;
      /** Label */
      label: string;
      /** Note */
      note: string;
      /** Reporting Period */
      reporting_period?: string | null;
      /** Retrieved On */
      retrieved_on?: string | null;
      /** Scope */
      scope?: string | null;
      /** Source Name */
      source_name: string;
      /** Source Url */
      source_url?: string | null;
      /** Value */
      value?: string | null;
    };
    /** AssessIn */
    AssessIn: {
      /** Intent */
      intent?: string | null;
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
      /** Space */
      space?: string | null;
      /** Transformer Distance M */
      transformer_distance_m?: number | null;
      /** Transformer Kva */
      transformer_kva?: number | null;
    };
    /** AssessOut */
    AssessOut: {
      /** Boundary Ambiguous */
      boundary_ambiguous: boolean;
      /** Confidence */
      confidence: string | null;
      /** District */
      district: string | null;
      /** Lgd District Code */
      lgd_district_code?: number | null;
      /** Requests */
      requests: number;
      /**
       * Site Id
       * Format: uuid
       */
      site_id: string;
      /** State */
      state: string | null;
      teaser: components["schemas"]["TeaserOut"] | null;
      /** Tier */
      tier: number | null;
      /** Tier Why */
      tier_why: string | null;
      /** Waitlist Reason */
      waitlist_reason: string | null;
      /** Waitlisted */
      waitlisted: boolean;
    };
    /** Band */
    Band: {
      /** P10 Kwh */
      p10_kwh: number;
      /** P50 Kwh */
      p50_kwh: number;
      /** P90 Kwh */
      p90_kwh: number;
    };
    /** BillIn */
    BillIn: {
      /** Board */
      board?: string | null;
      /** Confirmed */
      confirmed: boolean;
      /** Consumer Number */
      consumer_number?: string | null;
      /** Contract Demand */
      contract_demand?: number | null;
      /** Demand Unit */
      demand_unit?: ("kVA" | "kW") | null;
      /** History */
      history?: components["schemas"]["HistoryIn"][];
      /** Image Id */
      image_id?: string | null;
      /** Kwh */
      kwh: number;
      /** Period */
      period: string;
      /** Pf Amount Paise */
      pf_amount_paise?: number | null;
      /** Pf Effect */
      pf_effect?: ("penalty" | "incentive") | null;
      /** Power Factor */
      power_factor?: number | null;
      /** Recorded Demand */
      recorded_demand?: number | null;
      /** Tariff Category */
      tariff_category?: string | null;
      /** Tod Normal Kwh */
      tod_normal_kwh?: number | null;
      /** Tod Offpeak Kwh */
      tod_offpeak_kwh?: number | null;
      /** Tod Peak Kwh */
      tod_peak_kwh?: number | null;
    };
    /** BillMoney */
    BillMoney: {
      demand: components["schemas"]["DemandCard"] | null;
      /**
       * Period
       * Format: date
       */
      period: string;
      power_factor: components["schemas"]["PowerFactorCard"] | null;
      time_of_day: components["schemas"]["TodCard"] | null;
    };
    /** BillRef */
    BillRef: {
      /** Image Id */
      image_id: string | null;
      /** Kwh */
      kwh: number;
      /**
       * Period
       * Format: date
       */
      period: string;
    };
    /** BillSaveIn */
    BillSaveIn: {
      bill: components["schemas"]["BillIn"];
    };
    /** Body_upload_bill_image_api_internal_owner_bill_images_post */
    Body_upload_bill_image_api_internal_owner_bill_images_post: {
      /** File */
      file: string;
    };
    /** BreakevenPayload */
    BreakevenPayload: {
      /** Kwh Day */
      kwh_day: number;
      /** Kwh Year */
      kwh_year: number;
      /** Utilisation */
      utilisation: number;
    };
    /** ChargerOut */
    ChargerOut: {
      /** Connectors */
      connectors: components["schemas"]["ConnectorOut"][];
      /** Current Type */
      current_type: string | null;
      /** Id */
      id: number;
      /** Inferred */
      inferred: boolean;
      /** Label */
      label: string | null;
      /** Rated Power Kw */
      rated_power_kw: number | null;
      /** Status */
      status: string;
    };
    /** ClassRow */
    ClassRow: {
      /** Ev Total */
      ev_total: number;
      /** Group */
      group: string;
    };
    /** CompetitorRow */
    CompetitorRow: {
      /** Distance M */
      distance_m: number;
      /** Max Power Kw */
      max_power_kw: number;
      /** Name */
      name: string;
      /** Operator */
      operator: string;
      /** Points */
      points: number;
    };
    /** CompetitorsOut */
    CompetitorsOut: {
      /** By State */
      by_state: components["schemas"]["StateRow"][];
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Fetched From */
      fetched_from: string[];
      /** Top Operators */
      top_operators: components["schemas"]["OperatorRow"][];
      /** Total */
      total: number;
      /** Unplaced */
      unplaced: number;
    };
    /** CompetitorsPayload */
    CompetitorsPayload: {
      /** Nearest */
      nearest: components["schemas"]["CompetitorRow"][];
      /** Source */
      source: string;
      /** Within 3Km */
      within_3km: number;
    };
    /** ConnectorIn */
    ConnectorIn: {
      /** Power Kw */
      power_kw: number;
      /**
       * Standard
       * @enum {string}
       */
      standard: "CCS2" | "CCS1" | "CHAdeMO" | "Type 2 AC" | "GB/T" | "Other";
    };
    /** ConnectorOut */
    ConnectorOut: {
      /** Format */
      format: string | null;
      /** Id */
      id: number;
      /** Max Power Kw */
      max_power_kw: number | null;
      /** Standard */
      standard: string | null;
    };
    /** ConnectorView */
    ConnectorView: {
      /** Power Kw */
      power_kw: number;
      /** Standard */
      standard: string;
    };
    /** Counts */
    Counts: {
      /** Chargers */
      chargers: number;
      /** Connectors */
      connectors: number;
      /** Connectors Without Power */
      connectors_without_power: number;
      /** Operators */
      operators: number;
      /** Stations */
      stations: number;
      /** Unattributed */
      unattributed: number;
      /** Unplaced */
      unplaced: number;
    };
    /** CoverageOut */
    CoverageOut: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Note */
      note: string;
      /** Rule */
      rule: string;
      /** States */
      states: components["schemas"]["StateCoverageOut"][];
    };
    /** CpoRow */
    CpoRow: {
      /** Irr P50 Pct */
      irr_p50_pct: number;
      /** Margin Of Safety Pp */
      margin_of_safety_pp: number;
      /** Ocpi Roaming */
      ocpi_roaming: boolean;
      /** Operator */
      operator: string;
      /** Ours */
      ours: boolean;
      /** Platform Fee Paise Year */
      platform_fee_paise_year: number;
      /** Revenue Share Pct */
      revenue_share_pct: number;
      /** Uptime */
      uptime: string;
    };
    /**
     * CpoSourceOut
     * @description One scraped/roamed CPO source, for the console CPO panel (PLAN C.4).
     */
    CpoSourceOut: {
      /** Authorised */
      authorised: boolean;
      /** Blocking Reason */
      blocking_reason: string | null;
      /** Configured */
      configured: boolean;
      /** Connectors Last Run */
      connectors_last_run: number;
      /** Events Last Run */
      events_last_run: number;
      /** Kind */
      kind: string;
      /** Last Error */
      last_error: string | null;
      /** Last Success At */
      last_success_at: string | null;
      /** Pollable */
      pollable: boolean;
      /** Public Route */
      public_route: string | null;
      /** Rate Limit Per Minute */
      rate_limit_per_minute: number | null;
      /** Source */
      source: string;
      /** Stations Last Run */
      stations_last_run: number;
      /** Terms Note */
      terms_note: string | null;
      /** Terms Url */
      terms_url: string | null;
    };
    /** CpoSourcesOut */
    CpoSourcesOut: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Sources */
      sources: components["schemas"]["CpoSourceOut"][];
    };
    /** CredentialsIn */
    CredentialsIn: {
      /** Password */
      password: string;
      /** Phone */
      phone: string;
    };
    /** DemandCard */
    DemandCard: {
      /** Contract */
      contract: number;
      /** Recorded */
      recorded: number;
      /** Unit */
      unit: string;
      /** Used Share */
      used_share: number;
      /** Well Above Peak */
      well_above_peak: boolean;
    };
    /** DemandPayload */
    DemandPayload: {
      /** District Ev 2025 */
      district_ev_2025: number;
      /** District Growth Yoy Pct */
      district_growth_yoy_pct: number;
      /** Two Wheeler Share Pct */
      two_wheeler_share_pct: number;
      /** Vahan Snapshot */
      vahan_snapshot: string;
    };
    /** DistrictFacet */
    DistrictFacet: {
      /** District */
      district: string;
      /** Lgd District Code */
      lgd_district_code: number;
      /** Lgd State Code */
      lgd_state_code: number;
      /** Stations */
      stations: number;
    };
    /** DistrictVahanRow */
    DistrictVahanRow: {
      /** District */
      district: string;
      /** Ev Total */
      ev_total: number;
      /** Growth Pct */
      growth_pct: number | null;
      /** Lgd District Code */
      lgd_district_code: number | null;
      /** State */
      state: string;
    };
    /** FacetsOut */
    FacetsOut: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      counts: components["schemas"]["Counts"];
      /** Districts */
      districts: components["schemas"]["DistrictFacet"][];
      /** Operators */
      operators: components["schemas"]["OperatorFacet"][];
      /** States */
      states: components["schemas"]["StateFacet"][];
    };
    /** Features */
    Features: {
      /** Scraper Enabled */
      scraper_enabled: boolean;
    };
    /**
     * FieldSource
     * @description Where one field on the answer physically came from.
     */
    FieldSource: {
      /** Field */
      field: string;
      /** Note */
      note: string;
      /** Source */
      source: string;
      /** Value */
      value: string;
    };
    /** FinancialsPayload */
    FinancialsPayload: {
      anchor_note: components["schemas"]["AnchorNote"];
      /** Capex Paise */
      capex_paise: number;
      /** Energy Tariff Paise Kwh */
      energy_tariff_paise_kwh: number;
      /** Price Sensitivity */
      price_sensitivity: components["schemas"]["PriceSensitivityPoint"][];
      sanctioned_load: components["schemas"]["SanctionedLoad"];
      /** Scenarios */
      scenarios: components["schemas"]["Scenario"][];
      /** Selling Price Paise Kwh */
      selling_price_paise_kwh: number;
    };
    /** ForecastView */
    ForecastView: {
      band: components["schemas"]["Band"];
      /** Model Version */
      model_version: string;
      /** Month Of Operation */
      month_of_operation: number;
      /** Readings Used */
      readings_used: number;
      /**
       * Target Month
       * Format: date
       */
      target_month: string;
    };
    /** FunnelOut */
    FunnelOut: {
      /**
       * Billing Month
       * Format: date
       */
      billing_month: string;
      /** Cached Addresses */
      cached_addresses: number;
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Free Share */
      free_share: number | null;
      /** Levels */
      levels: components["schemas"]["LevelOut"][];
      /** Queue Open */
      queue_open: number;
      /** Queue Rejected */
      queue_rejected: number;
      /** Queue Resolved */
      queue_resolved: number;
      /** Resolved */
      resolved: number;
      /** Spend */
      spend: components["schemas"]["SpendOut"][];
    };
    /** GridDetailsIn */
    GridDetailsIn: {
      /** Connected Load Kw */
      connected_load_kw?: number | null;
      /**
       * Consent Private
       * @constant
       */
      consent_private: true;
      /**
       * Effective On
       * Format: date
       */
      effective_on: string;
      /** Expected Revision Id */
      expected_revision_id?: number | null;
      /** Sanctioned Load Kva */
      sanctioned_load_kva?: number | null;
      /**
       * Transformer Ownership
       * @default unknown
       * @enum {string}
       */
      transformer_ownership: "own" | "shared" | "unknown";
      /** Transformer Rating Kva */
      transformer_rating_kva?: number | null;
    };
    /** GridDetailsOut */
    GridDetailsOut: {
      /** Connected Load Kw */
      connected_load_kw: number | null;
      /**
       * Effective On
       * Format: date
       */
      effective_on: string;
      /** Id */
      id: number;
      /**
       * Recorded At
       * Format: date-time
       */
      recorded_at: string;
      /** Sanctioned Load Kva */
      sanctioned_load_kva: number | null;
      /** Supersedes Id */
      supersedes_id: number | null;
      /**
       * Transformer Ownership
       * @enum {string}
       */
      transformer_ownership: "own" | "shared" | "unknown";
      /** Transformer Rating Kva */
      transformer_rating_kva: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HardwarePayload */
    HardwarePayload: {
      /** Connectors */
      connectors: number;
      /** Rated Kw Each */
      rated_kw_each: number;
      /** Sanctioned Kva Full */
      sanctioned_kva_full: number;
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
    };
    /** HistoryIn */
    HistoryIn: {
      /** Kwh */
      kwh: number;
      /** Period */
      period: string;
    };
    /** ImageOut */
    ImageOut: {
      /** Content Type */
      content_type: string;
      /** Extractor */
      extractor: string;
      /**
       * Image Id
       * Format: uuid
       */
      image_id: string;
      /** Size Bytes */
      size_bytes: number;
      /** Suggested */
      suggested: {
        [key: string]: string | number | null;
      };
    };
    /**
     * InputOut
     * @description One external thing only a human can supply: a key, an endpoint, a file.
     *
     *     The status is read from live settings at request time, so pasting a line
     *     into ``.env`` and restarting the API flips the row on its own - the page
     *     can never claim a key exists that the process cannot see.
     */
    InputOut: {
      /** Detail */
      detail: string;
      /** Env Vars */
      env_vars: string[];
      /** How To Get */
      how_to_get: string;
      /** Kind */
      kind: string;
      /** Name */
      name: string;
      /** Needed For */
      needed_for: string;
      status: components["schemas"]["InputStatus"];
    };
    /**
     * InputStatus
     * @enum {string}
     */
    InputStatus: "configured" | "missing" | "attention" | "later";
    /** LastMonth */
    LastMonth: {
      /** Kwh */
      kwh: number;
      /** Month Of Operation */
      month_of_operation: number;
      /**
       * Period
       * Format: date
       */
      period: string;
    };
    /**
     * LayerOut
     * @description Provenance of the map data itself - PLAN C.5's data-vintage row.
     */
    LayerOut: {
      /**
       * Downloaded At
       * Format: date-time
       */
      downloaded_at: string;
      /** Feature Count */
      feature_count: number;
      /** Licence */
      licence: string;
      /** Name */
      name: string;
      /** Source Url */
      source_url: string;
    };
    /** LedgerRow */
    LedgerRow: {
      /** Item */
      item: string;
      /** Source */
      source: string;
      /** Unverified */
      unverified: boolean;
      /** Value */
      value: string;
    };
    /**
     * LevelOut
     * @description One cascade level's share of the cache.
     */
    LevelOut: {
      /** Resolved */
      resolved: number;
      /** Source */
      source: string;
      /** Unresolved */
      unresolved: number;
    };
    /** ListingOut */
    ListingOut: {
      /**
       * First Seen At
       * Format: date-time
       */
      first_seen_at: string;
      /**
       * Last Seen At
       * Format: date-time
       */
      last_seen_at: string;
      /** Source */
      source: string;
      /** Source Key */
      source_key: string;
      /** Source Name */
      source_name: string | null;
      /** Source Operator */
      source_operator: string | null;
    };
    /** LoginIn */
    LoginIn: {
      /** Password */
      password: string;
    };
    /** MeOut */
    MeOut: {
      /** Phone Masked */
      phone_masked: string;
      /** Station Count */
      station_count: number;
    };
    /** MilestoneOut */
    MilestoneOut: {
      /** Evidence */
      evidence: string;
      /** Order */
      order: number;
      /** Part */
      part: string;
      status: components["schemas"]["Status"];
      /** Title */
      title: string;
      /** To Close */
      to_close?: string | null;
      /** What */
      what: string;
    };
    /** ModelPoint */
    ModelPoint: {
      band: components["schemas"]["Band"];
      /** Month Of Operation */
      month_of_operation: number;
    };
    /** NeighbourOut */
    NeighbourOut: {
      /** Distance M */
      distance_m: number;
      /** Lgd District Code */
      lgd_district_code: number;
      /** Name */
      name: string;
      /** State Name */
      state_name: string;
    };
    /** OnboardIn */
    OnboardIn: {
      bill: components["schemas"]["BillIn"];
      /** Connectors */
      connectors: components["schemas"]["ConnectorIn"][];
      /** Consent Aggregate */
      consent_aggregate: boolean;
      /** Meter Answer */
      meter_answer?: ("separate" | "shared" | "unsure") | null;
      station: components["schemas"]["StationIn"];
    };
    /** Operator */
    Operator: {
      /** Operator */
      operator: string;
    };
    /** OperatorFacet */
    OperatorFacet: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Stations */
      stations: number;
    };
    /** OperatorRow */
    OperatorRow: {
      /** Dc Fast */
      dc_fast: number;
      /** Operator */
      operator: string;
      /** Stations */
      stations: number;
    };
    /** OutageIn */
    OutageIn: {
      /** Approximate Hours */
      approximate_hours?: number | null;
      /**
       * Consent Private
       * @constant
       */
      consent_private: true;
      /** Expected Revision Id */
      expected_revision_id?: number | null;
      /**
       * Month
       * Format: date
       */
      month: string;
    };
    /** OutageOut */
    OutageOut: {
      /** Approximate Hours */
      approximate_hours: number | null;
      /** Id */
      id: number;
      /**
       * Month
       * Format: date
       */
      month: string;
      /**
       * Recorded At
       * Format: date-time
       */
      recorded_at: string;
      /** Supersedes Id */
      supersedes_id: number | null;
    };
    /** OwnerAreaOut */
    OwnerAreaOut: {
      /** District */
      district: string | null;
      /** Items */
      items: components["schemas"]["AreaItem"][];
      /** Snapshot Sha256 */
      snapshot_sha256: string | null;
      /** State */
      state: string | null;
      /**
       * Version
       * @default owner_area_v1
       * @constant
       */
      version: "owner_area_v1";
      /** Versions */
      versions?: {
        [key: string]: string;
      };
    };
    /** OwnerGridOut */
    OwnerGridOut: {
      /** Consent Private */
      consent_private: boolean;
      details: components["schemas"]["GridDetailsOut"] | null;
      /** Outages */
      outages: components["schemas"]["OutageOut"][];
      /** Storage Available */
      storage_available: boolean;
      /** Storage Reason */
      storage_reason?: string | null;
      /**
       * Version
       * @default owner_grid_v1
       * @constant
       */
      version: "owner_grid_v1";
      /** Versions */
      versions?: {
        [key: string]: string;
      };
    };
    /** PeerBandPoint */
    PeerBandPoint: {
      band: components["schemas"]["Band"];
      /** Month Of Operation */
      month_of_operation: number;
      /** N */
      n: number;
    };
    /** PeerView */
    PeerView: {
      /** Available */
      available: boolean;
      /** Band */
      band: components["schemas"]["PeerBandPoint"][];
      /** Basis */
      basis: string;
      latest_band: components["schemas"]["Band"] | null;
      /** Message */
      message: string;
      /** Min Required */
      min_required: number;
      /** Model Curve */
      model_curve: components["schemas"]["ModelPoint"][];
      /** N */
      n: number;
      /** Percentile */
      percentile: number | null;
      /** Reason */
      reason: string | null;
    };
    /** PointOut */
    PointOut: {
      /** Boundary Ambiguous */
      boundary_ambiguous: boolean;
      /** Confidence */
      confidence: string;
      /** Distance M */
      distance_m: number;
      /** District */
      district: string | null;
      /** Fields */
      fields: components["schemas"]["FieldSource"][];
      /** Lat */
      lat: number;
      /** Layers */
      layers: components["schemas"]["LayerOut"][];
      /** Lgd District Code */
      lgd_district_code: number | null;
      /** Lgd State Code */
      lgd_state_code: number | null;
      /** Lng */
      lng: number;
      /** Method */
      method: string;
      neighbour: components["schemas"]["NeighbourOut"] | null;
      /** Overridden District */
      overridden_district: string | null;
      /** Pin Conflict */
      pin_conflict: boolean;
      /** Pincode At Point */
      pincode_at_point: string[];
      /** Reasons */
      reasons: string[];
      /** Resolved */
      resolved: boolean;
      /** State Name */
      state_name: string | null;
      /** Steps */
      steps: components["schemas"]["Step"][];
      /** Supplied Pincode */
      supplied_pincode: string | null;
    };
    /** PollerHealthOut */
    PollerHealthOut: {
      /** Alive */
      alive: boolean;
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Never Run */
      never_run: boolean;
      /** Sources */
      sources: components["schemas"]["SourceHealthOut"][];
      /** Stale Sources */
      stale_sources: string[];
      /** Threshold Minutes */
      threshold_minutes: number;
    };
    /** PortfolioRow */
    PortfolioRow: {
      /** Change Pct */
      change_pct: number | null;
      /** District */
      district: string | null;
      /** Last Kwh */
      last_kwh: number | null;
      /** Last Period */
      last_period: string | null;
      /** Name */
      name: string;
      /** Peer N */
      peer_n: number;
      /** Peer Percentile */
      peer_percentile: number | null;
      /** Possibly Shared */
      possibly_shared: boolean;
      /** Station Id */
      station_id: number;
    };
    /** PowerFactorCard */
    PowerFactorCard: {
      /** Amount Paise */
      amount_paise: number | null;
      /** Effect */
      effect: string | null;
      /** Power Factor */
      power_factor: number | null;
    };
    /** PriceSensitivityPoint */
    PriceSensitivityPoint: {
      /** Breakeven Utilisation */
      breakeven_utilisation: number;
      /** Price Paise Kwh */
      price_paise_kwh: number;
    };
    /** ProgressOut */
    ProgressOut: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Inputs */
      inputs: components["schemas"]["InputOut"][];
      /** Milestones */
      milestones: components["schemas"]["MilestoneOut"][];
      /** Summary */
      summary: string;
    };
    /** ProvenanceRow */
    ProvenanceRow: {
      /** Label */
      label: string;
      /**
       * Unverified
       * @default false
       */
      unverified: boolean;
      /** Value */
      value: string;
    };
    /** PublicContextPayload */
    PublicContextPayload: {
      /**
       * Grid Conditions
       * @default []
       */
      grid_conditions: string[];
      /** Snapshot Sha256 */
      snapshot_sha256: string;
      /** Sources */
      sources: components["schemas"]["PublicSourceContext"][];
      /**
       * Version
       * @default public_context_v1
       * @constant
       */
      version: "public_context_v1";
    };
    /** PublicSourceContext */
    PublicSourceContext: {
      /** Dataset */
      dataset: string;
      /** Licence */
      licence?: string | null;
      /** Licence Url */
      licence_url?: string | null;
      /** Retrieved On */
      retrieved_on?: string | null;
      /** Source Name */
      source_name: string;
      /** Source Sha256 */
      source_sha256?: string | null;
      /** Source Url */
      source_url?: string | null;
      /** Status */
      status: string;
      /** Time Coverage */
      time_coverage?: string | null;
      /** Transformation Version */
      transformation_version?: string | null;
    };
    /** QueueItemOut */
    QueueItemOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Hits */
      hits: number;
      /** Id */
      id: number;
      /** Lat */
      lat: number | null;
      /** Lng */
      lng: number | null;
      /** Normalised Input */
      normalised_input: string;
      /** Pincode */
      pincode: string | null;
      /** Raw Input */
      raw_input: string;
      /** Reason */
      reason: string | null;
      /** Status */
      status: string;
    };
    /** QueueOut */
    QueueOut: {
      /** Items */
      items: components["schemas"]["QueueItemOut"][];
      /** Open Count */
      open_count: number;
    };
    /** Readiness */
    Readiness: {
      /** Database */
      database: string;
      /** Env */
      env: string;
      /** Paid Providers Enabled */
      paid_providers_enabled: string[];
      /** Postgis */
      postgis: string;
    };
    /** RejectIn */
    RejectIn: {
      /** Note */
      note?: string | null;
    };
    /** ReportPayload */
    ReportPayload: {
      breakeven: components["schemas"]["BreakevenPayload"];
      competitors: components["schemas"]["CompetitorsPayload"];
      /** Cpo */
      cpo: components["schemas"]["CpoRow"][];
      demand: components["schemas"]["DemandPayload"];
      /** Demo */
      demo: boolean;
      financials: components["schemas"]["FinancialsPayload"];
      hardware: components["schemas"]["HardwarePayload"];
      /** Ledger */
      ledger: components["schemas"]["LedgerRow"][];
      /** Margin Of Safety Pp */
      margin_of_safety_pp: number;
      predicted: components["schemas"]["UtilisationBand"];
      /** Provenance */
      provenance: components["schemas"]["ProvenanceRow"][];
      public_context?: components["schemas"]["PublicContextPayload"] | null;
      /** Report Id */
      report_id: string;
      site: components["schemas"]["SitePayload"];
      /** Site Facts */
      site_facts: components["schemas"]["SiteFact"][];
      verdict: components["schemas"]["VerdictPayload"];
    };
    /** ResolveIn */
    ResolveIn: {
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
      /** Note */
      note?: string | null;
    };
    /** SanctionedLoad */
    SanctionedLoad: {
      /** Buffered Kva */
      buffered_kva: number;
      /** Full Kva */
      full_kva: number;
      /** Recommended Kva */
      recommended_kva: number;
      /** Recommended Label */
      recommended_label: string;
      /** Saving Paise Year */
      saving_paise_year: number;
    };
    /** SavedOut */
    SavedOut: {
      /**
       * Period
       * Format: date
       */
      period: string;
      /** Station Id */
      station_id: number;
    };
    /** Scenario */
    Scenario: {
      /** Irr Pct */
      irr_pct: number | null;
      /** Kwh Year */
      kwh_year: number;
      /** Label */
      label: string;
      /** Npv Paise */
      npv_paise: number;
      /** Payback Years */
      payback_years: number | null;
      /** Utilisation */
      utilisation: number;
    };
    /** SeriesPoint */
    SeriesPoint: {
      /** Kwh */
      kwh: number;
      /** Month Of Operation */
      month_of_operation: number;
      /**
       * Period
       * Format: date
       */
      period: string;
    };
    /** SiteFact */
    SiteFact: {
      /** Label */
      label: string;
      /** Source */
      source: string;
      /** Unverified */
      unverified: boolean;
      /** Value */
      value: string;
    };
    /** SitePayload */
    SitePayload: {
      /** Archetype */
      archetype: string;
      /**
       * Data Tier
       * @enum {integer}
       */
      data_tier: 1 | 2 | 3;
      /** District */
      district: string;
      /** Lat */
      lat: number;
      /** Lgd District Code */
      lgd_district_code: number;
      /** Line */
      line: string;
      /** Lng */
      lng: number;
      /** Name */
      name: string;
    };
    /** SourceHealthOut */
    SourceHealthOut: {
      /** Blocking Reason */
      blocking_reason: string | null;
      /** Connectors Last Run */
      connectors_last_run: number;
      /** Events Last Run */
      events_last_run: number;
      /** Last Error */
      last_error: string | null;
      /** Last Success At */
      last_success_at: string | null;
      /** Pollable */
      pollable: boolean;
      /** Raw Pages Last Run */
      raw_pages_last_run: number;
      /** Silent For Seconds */
      silent_for_seconds: number | null;
      /** Source */
      source: string;
      /** Stale */
      stale: boolean;
    };
    /** SpendOut */
    SpendOut: {
      /** Calls */
      calls: number;
      /** Cost Paise */
      cost_paise: number;
      /** Provider */
      provider: string;
    };
    /** StateCoverageOut */
    StateCoverageOut: {
      /** Districts */
      districts: number;
      /** Focus */
      focus: boolean;
      /** Has Competitor Poll */
      has_competitor_poll: boolean;
      /** Has Osm Road Quality */
      has_osm_road_quality: boolean;
      /** Has Tariff Data */
      has_tariff_data: boolean;
      /** Has Vahan Data */
      has_vahan_data: boolean;
      /** Lgd State Code */
      lgd_state_code: number;
      /** State */
      state: string;
      /**
       * Tier
       * @description 1 = full report · 2 = tariff audit only · 3 = waitlist
       */
      tier: number;
      /** Why */
      why: string;
    };
    /** StateFacet */
    StateFacet: {
      /** Lgd State Code */
      lgd_state_code: number;
      /** State */
      state: string;
      /** Stations */
      stations: number;
    };
    /** StateRow */
    StateRow: {
      /** Lgd State Code */
      lgd_state_code: number;
      /** State */
      state: string;
      /** Stations */
      stations: number;
    };
    /** StateVahanRow */
    StateVahanRow: {
      /** Districts */
      districts: number;
      /** Ev Total */
      ev_total: number;
      /** Growth Pct */
      growth_pct: number | null;
      /** Lgd State Code */
      lgd_state_code: number;
      /** State */
      state: string;
    };
    /** StationDetail */
    StationDetail: {
      /** Access */
      access: string | null;
      /** Address */
      address: string | null;
      /** Chargers */
      chargers: components["schemas"]["ChargerOut"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Is Operational */
      is_operational: boolean | null;
      /** Listings */
      listings: components["schemas"]["ListingOut"][];
      /** Postcode */
      postcode: string | null;
      station: components["schemas"]["StationRow"];
    };
    /** StationHome */
    StationHome: {
      /** Bills */
      bills: components["schemas"]["BillRef"][];
      forecast: components["schemas"]["ForecastView"] | null;
      last_month: components["schemas"]["LastMonth"] | null;
      money: components["schemas"]["BillMoney"] | null;
      peer: components["schemas"]["PeerView"];
      /** Series */
      series: components["schemas"]["SeriesPoint"][];
      station: components["schemas"]["StationView"];
      /** Track Record */
      track_record: components["schemas"]["TrackRow"][];
    };
    /** StationIn */
    StationIn: {
      /** Address */
      address?: string | null;
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
      /** Name */
      name: string;
      /** Went Live */
      went_live: string;
    };
    /** StationRow */
    StationRow: {
      /** Chargers */
      chargers: number;
      /** Connectors */
      connectors: number;
      /** Dc Fast */
      dc_fast: boolean;
      /** District */
      district: string | null;
      /** Id */
      id: number;
      /** Lat */
      lat: number;
      /** Listings */
      listings: number;
      /** Lng */
      lng: number;
      /** Max Power Kw */
      max_power_kw: number | null;
      /** Name */
      name: string | null;
      /** Operator */
      operator: string | null;
      /** Operator Confirmed */
      operator_confirmed: boolean;
      /** State */
      state: string | null;
      /** Town */
      town: string | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** StationView */
    StationView: {
      /** Connectors */
      connectors: components["schemas"]["ConnectorView"][];
      /** District */
      district: string | null;
      /** Id */
      id: number;
      /** Meter Type */
      meter_type: string;
      /** Name */
      name: string;
      /** Possibly Shared */
      possibly_shared: boolean;
      /** State */
      state: string | null;
      /**
       * Went Live
       * Format: date
       */
      went_live: string;
    };
    /** StationsOut */
    StationsOut: {
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Pages */
      pages: number;
      /** Stations */
      stations: components["schemas"]["StationRow"][];
      /** Total */
      total: number;
    };
    /**
     * Status
     * @enum {string}
     */
    Status: "done" | "code_done" | "partial" | "next" | "parked" | "not_started";
    /**
     * Step
     * @description One question the resolver asked, and where it went for the answer.
     */
    Step: {
      /** Answer */
      answer: string;
      /**
       * Decisive
       * @default false
       */
      decisive: boolean;
      /** Looked In */
      looked_in: string;
      /** N */
      n: number;
      /** Question */
      question: string;
      /** Using */
      using: string;
    };
    /** TableOut */
    TableOut: {
      /** Empty Means */
      empty_means?: string | null;
      /** Filled By */
      filled_by: string;
      /** Group */
      group: string;
      /** Rows */
      rows: number;
      /** Table */
      table: string;
      /** What */
      what: string;
    };
    /** TablesOut */
    TablesOut: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Extension Tables */
      extension_tables: string[];
      /** Tables */
      tables: components["schemas"]["TableOut"][];
      /** Undocumented */
      undocumented: string[];
    };
    /** TapOut */
    TapOut: {
      /** Effect */
      effect: string;
      /** Label */
      label: string;
      /** Provided */
      provided: boolean;
    };
    /** TeaserOut */
    TeaserOut: {
      /** Breakeven Kwh Day */
      breakeven_kwh_day: number | null;
      /** Breakeven Kwh Year */
      breakeven_kwh_year: number | null;
      /** Breakeven Utilisation */
      breakeven_utilisation: number | null;
      /** Connectors */
      connectors: number;
      /** Energy Tariff Paise Per Kwh */
      energy_tariff_paise_per_kwh: number;
      /** Notes */
      notes: string[];
      /** Rated Kw Each */
      rated_kw_each: number;
      /** Sanctioned Kva */
      sanctioned_kva: number;
      /** Selling Paise Per Kwh */
      selling_paise_per_kwh: number;
      /** Taps */
      taps: components["schemas"]["TapOut"][];
      /** Tariff Source */
      tariff_source: string;
    };
    /** TodCard */
    TodCard: {
      /** Normal Kwh */
      normal_kwh: number | null;
      /** Offpeak Kwh */
      offpeak_kwh: number | null;
      /** Peak Kwh */
      peak_kwh: number | null;
    };
    /** TrackRow */
    TrackRow: {
      /** Actual Kwh */
      actual_kwh: number;
      band: components["schemas"]["Band"];
      /** Error Pct */
      error_pct: number;
      /**
       * Forecast Made From
       * Format: date
       */
      forecast_made_from: string;
      /** Inside Range */
      inside_range: boolean;
      /** Model Version */
      model_version: string;
      /**
       * Target Month
       * Format: date
       */
      target_month: string;
    };
    /** UtilisationBand */
    UtilisationBand: {
      /** Model Version */
      model_version: string;
      /** Modelled Not Measured */
      modelled_not_measured: boolean;
      /** P10 */
      p10: number;
      /** P50 */
      p50: number;
      /** P90 */
      p90: number;
    };
    /** VahanOut */
    VahanOut: {
      /** By Class */
      by_class: components["schemas"]["ClassRow"][];
      /** By State */
      by_state: components["schemas"]["StateVahanRow"][];
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Display Period */
      display_period: string | null;
      /** Periods */
      periods: string[];
      /** Snapshot Date */
      snapshot_date: string | null;
      /** Top Districts */
      top_districts: components["schemas"]["DistrictVahanRow"][];
      /** Total Rows */
      total_rows: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VerdictPayload */
    VerdictPayload: {
      /** Reason */
      reason: string;
      /**
       * Value
       * @enum {string}
       */
      value: "build" | "conditional" | "dont";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  assess_api_internal_assess_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssessIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssessOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  competitors_api_internal_competitors_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompetitorsOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_internal_console_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Operator"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_internal_console_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_api_internal_console_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Operator"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  features_api_internal_features_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Features"];
        };
      };
    };
  };
  geocoding_funnel_api_internal_geocoding_funnel_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FunnelOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  geocoding_queue_api_internal_geocoding_queue_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueueOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reject_job_api_internal_geocoding_queue__queue_id__reject_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        queue_id: number;
      };
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RejectIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueueItemOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  resolve_job_api_internal_geocoding_queue__queue_id__resolve_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        queue_id: number;
      };
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolveIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueueItemOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  healthz_api_internal_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  lookup_coverage_api_internal_lookup_coverage_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoverageOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  lookup_point_api_internal_lookup_point_get: {
    parameters: {
      query: {
        /** @description India's bounding box, roughly */
        lat: number;
        lng: number;
        pincode?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PointOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  lookup_tables_api_internal_lookup_tables_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TablesOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  facets_api_internal_network_facets_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FacetsOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_stations_api_internal_network_stations_get: {
    parameters: {
      query?: {
        /** @description LGD state code */
        state?: number | null;
        /** @description LGD district code */
        district?: number | null;
        /** @description CPO id; 0 = unattributed */
        operator?: number | null;
        q?: string;
        sort?: "name" | "connectors" | "power" | "updated";
        page?: number;
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StationsOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  station_detail_api_internal_network_stations__station_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        station_id: number;
      };
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StationDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_bill_image_api_internal_owner_bill_images_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_bill_image_api_internal_owner_bill_images_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImageOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bill_image_api_internal_owner_bill_images__image_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        image_id: string;
      };
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_bill_image_api_internal_owner_bill_images__image_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        image_id: string;
      };
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_internal_owner_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CredentialsIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_internal_owner_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_api_internal_owner_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  erase_me_api_internal_owner_me_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  onboard_api_internal_owner_onboard_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OnboardIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  signup_api_internal_owner_signup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CredentialsIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_stations_api_internal_owner_stations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioRow"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  owner_area_api_internal_owner_stations__station_id__area_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        station_id: number;
      };
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OwnerAreaOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  save_bill_api_internal_owner_stations__station_id__bills_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        station_id: number;
      };
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BillSaveIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  owner_grid_api_internal_owner_stations__station_id__grid_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        station_id: number;
      };
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OwnerGridOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  owner_grid_save_api_internal_owner_stations__station_id__grid_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        station_id: number;
      };
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GridDetailsIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OwnerGridOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  owner_grid_withdraw_api_internal_owner_stations__station_id__grid_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        station_id: number;
      };
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  home_api_internal_owner_stations__station_id__home_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        station_id: number;
      };
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StationHome"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  owner_outage_save_api_internal_owner_stations__station_id__outages_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        station_id: number;
      };
      cookie?: {
        evsite_owner?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OutageIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OwnerGridOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  poller_alive_api_internal_poller_alive_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AliveOut"];
        };
      };
    };
  };
  poller_health_endpoint_api_internal_poller_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PollerHealthOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  progress_api_internal_progress_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgressOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  readyz_api_internal_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Readiness"];
        };
      };
    };
  };
  report_api_internal_reports__report_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        report_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportPayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cpo_sources_endpoint_api_internal_sources_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CpoSourcesOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  vahan_api_internal_vahan_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VahanOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  ping_api_v1_ping_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
