/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/internal/console/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_internal_console_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/console/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Clear the cookie.
     *
     *     Deliberately unguarded: signing out must work even from a session that has
     *     already expired, and refusing to clear a cookie helps nobody. The attribute
     *     set here must match the login cookie or the browser will keep the old one.
     */
    post: operations["logout_api_internal_console_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/console/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Me
     * @description Who am I. The SPA calls this on load to decide login vs console.
     */
    get: operations["me_api_internal_console_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Healthz
     * @description Liveness only. Does not touch the database.
     */
    get: operations["healthz_api_internal_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/poller/alive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Poller Alive
     * @description Unauthenticated liveness for an external uptime monitor.
     *
     *     Returns 503 when nothing is being recorded, so a generic "is this URL
     *     healthy" checker becomes a second alarm that does not depend on our own
     *     logging, our own alerting, or our own process being alive to send it.
     *
     *     Deliberately says nothing else. Which networks we poll, and what they last
     *     told us, is console data and lives behind the guard.
     */
    get: operations["poller_alive_api_internal_poller_alive_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/poller/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Poller Health Endpoint */
    get: operations["poller_health_endpoint_api_internal_poller_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readyz
     * @description Readiness: database reachable and PostGIS actually installed.
     *
     *     PostGIS is checked explicitly because every spatial query in Part 1
     *     silently becomes an error without it, and the failure surfaces far from
     *     the cause.
     */
    get: operations["readyz_api_internal_readyz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/internal/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cpo Sources Endpoint
     * @description The CPO/source registry with governance + measured status side by side.
     *
     *     Feeds the console CPO panel: which networks we scrape, whether each is
     *     authorised and configured, and what our own poller last saw from it -
     *     uptime we measured, not uptime the operator claimed.
     */
    get: operations["cpo_sources_endpoint_api_internal_sources_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ping */
    get: operations["ping_api_v1_ping_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AliveOut */
    AliveOut: {
      /** Alive */
      alive: boolean;
      /** Never Run */
      never_run: boolean;
    };
    /**
     * CpoSourceOut
     * @description One scraped/roamed CPO source, for the console CPO panel (PLAN C.4).
     */
    CpoSourceOut: {
      /** Authorised */
      authorised: boolean;
      /** Blocking Reason */
      blocking_reason: string | null;
      /** Configured */
      configured: boolean;
      /** Connectors Last Run */
      connectors_last_run: number;
      /** Events Last Run */
      events_last_run: number;
      /** Kind */
      kind: string;
      /** Last Error */
      last_error: string | null;
      /** Last Success At */
      last_success_at: string | null;
      /** Pollable */
      pollable: boolean;
      /** Rate Limit Per Minute */
      rate_limit_per_minute: number | null;
      /** Source */
      source: string;
      /** Stations Last Run */
      stations_last_run: number;
      /** Terms Note */
      terms_note: string | null;
      /** Terms Url */
      terms_url: string | null;
    };
    /** CpoSourcesOut */
    CpoSourcesOut: {
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Sources */
      sources: components["schemas"]["CpoSourceOut"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
    };
    /** LoginIn */
    LoginIn: {
      /** Password */
      password: string;
    };
    /** Operator */
    Operator: {
      /** Operator */
      operator: string;
    };
    /** PollerHealthOut */
    PollerHealthOut: {
      /** Alive */
      alive: boolean;
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
      /** Never Run */
      never_run: boolean;
      /** Sources */
      sources: components["schemas"]["SourceHealthOut"][];
      /** Stale Sources */
      stale_sources: string[];
      /** Threshold Minutes */
      threshold_minutes: number;
    };
    /** Readiness */
    Readiness: {
      /** Database */
      database: string;
      /** Env */
      env: string;
      /** Paid Providers Enabled */
      paid_providers_enabled: string[];
      /** Postgis */
      postgis: string;
    };
    /** SourceHealthOut */
    SourceHealthOut: {
      /** Blocking Reason */
      blocking_reason: string | null;
      /** Connectors Last Run */
      connectors_last_run: number;
      /** Events Last Run */
      events_last_run: number;
      /** Last Error */
      last_error: string | null;
      /** Last Success At */
      last_success_at: string | null;
      /** Pollable */
      pollable: boolean;
      /** Raw Pages Last Run */
      raw_pages_last_run: number;
      /** Silent For Seconds */
      silent_for_seconds: number | null;
      /** Source */
      source: string;
      /** Stale */
      stale: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login_api_internal_console_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Operator"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_internal_console_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_api_internal_console_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Operator"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  healthz_api_internal_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  poller_alive_api_internal_poller_alive_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AliveOut"];
        };
      };
    };
  };
  poller_health_endpoint_api_internal_poller_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PollerHealthOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  readyz_api_internal_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Readiness"];
        };
      };
    };
  };
  cpo_sources_endpoint_api_internal_sources_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        evsite_console?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CpoSourcesOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  ping_api_v1_ping_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
