"""PART 0.1 - charger_status_events (partitioned) + poll_runs.

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-12

The event table is RANGE-partitioned by month on ``observed_at``, per
PLAN 0.1. A DEFAULT partition is created deliberately: if partition
maintenance ever falls behind, an insert must still succeed. Losing a poll
because nobody ran a maintenance job is exactly the failure this whole table
exists to prevent - a slightly untidy default partition is a far cheaper
problem than a hole in the record.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Months of partitions to pre-create, starting this month.
MONTHS_AHEAD = 6


def upgrade() -> None:
    op.create_table(
        "poll_runs",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("source", sa.String(64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("outcome", sa.String(16), nullable=False),
        sa.Column("events_written", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("stations_seen", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("error", sa.Text()),
        sa.Column("duration_ms", sa.Integer()),
    )
    op.create_index("ix_poll_runs_source_started", "poll_runs", ["source", "started_at"])
    op.create_index("ix_poll_runs_started", "poll_runs", ["started_at"])

    # Partitioned parent. The PK must include the partition key.
    op.execute(
        """
        CREATE TABLE charger_status_events (
            id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
            observed_at       TIMESTAMPTZ NOT NULL,
            source            VARCHAR(64) NOT NULL,
            source_station_id VARCHAR(255) NOT NULL,
            connector_id      VARCHAR(255) NOT NULL,
            status            VARCHAR(16) NOT NULL,
            raw_payload       JSONB,
            poll_run_id       UUID,
            ingested_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (id, observed_at)
        ) PARTITION BY RANGE (observed_at)
        """
    )

    op.execute(
        """
        CREATE INDEX ix_cse_connector_time
            ON charger_status_events (source, source_station_id, connector_id, observed_at)
        """
    )
    op.execute("CREATE INDEX ix_cse_observed_at ON charger_status_events (observed_at)")

    conn = op.get_bind()
    for statement in _partition_statements(MONTHS_AHEAD):
        conn.execute(sa.text(statement))

    # Backstop. Never let a missing partition reject a poll.
    op.execute(
        "CREATE TABLE charger_status_events_default PARTITION OF charger_status_events DEFAULT"
    )

    # Append-only, enforced by the database rather than by convention
    # (AGENTS.md constraint 3). Rules are inherited by partitions.
    op.execute(
        """
        CREATE RULE charger_status_events_no_update AS
            ON UPDATE TO charger_status_events DO INSTEAD NOTHING;
        CREATE RULE charger_status_events_no_delete AS
            ON DELETE TO charger_status_events DO INSTEAD NOTHING;
        """
    )

    op.execute(
        """
        INSERT INTO schema_version (version, note)
        VALUES (3, 'PART 0.1 poller: charger_status_events (monthly partitions) + poll_runs')
        """
    )


def _partition_statements(months: int) -> list[str]:
    """Monthly partitions from the start of the current month.

    Generated in SQL from ``date_trunc(now())`` rather than from a Python
    date, so re-running this migration on a different day still produces a
    contiguous, gap-free set.
    """
    statements: list[str] = []
    for offset in range(months):
        statements.append(
            f"""
            DO $$
            DECLARE
                start_at DATE := (date_trunc('month', now()) + INTERVAL '{offset} month')::date;
                end_at   DATE := (date_trunc('month', now()) + INTERVAL '{offset + 1} month')::date;
                part     TEXT := 'charger_status_events_' || to_char(start_at, 'YYYY_MM');
            BEGIN
                EXECUTE format(
                    'CREATE TABLE IF NOT EXISTS %I PARTITION OF charger_status_events '
                    'FOR VALUES FROM (%L) TO (%L)', part, start_at, end_at
                );
            END $$;
            """
        )
    return statements


def downgrade() -> None:
    op.execute("DROP RULE IF EXISTS charger_status_events_no_update ON charger_status_events")
    op.execute("DROP RULE IF EXISTS charger_status_events_no_delete ON charger_status_events")
    op.execute("DROP TABLE IF EXISTS charger_status_events CASCADE")  # cascades to partitions
    op.drop_table("poll_runs")
    op.execute("DELETE FROM schema_version WHERE version = 3")
