"""PART 0.1 - raw archive (1) + derived transition log (2).

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-12

PLAN 0.1 was revised to separate capture from query:

  * ``poll_raw_payloads``      NEW. Lossless, one row per response page per
                               cycle. Partitioned monthly, append-only,
                               deliberately unindexed on the payload.
  * ``charger_status_events``  becomes the DERIVED transition log: gains
                               ``transition``, loses ``raw_payload`` (the
                               archive holds it now).
  * ``connector_state``        NEW. A rebuildable cache of the latest status
                               per connector, so the five-minute derivation is
                               O(connectors) rather than O(history).

Dropping ``raw_payload`` is destructive, so ``upgrade()`` refuses to run if
the table has any rows. On a populated database the payloads must be copied
into the archive first - this migration will not decide that for you.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Months of partitions to pre-create, starting this month.
MONTHS_AHEAD = 6


def upgrade() -> None:
    conn = op.get_bind()

    existing = conn.execute(sa.text("SELECT count(*) FROM charger_status_events")).scalar_one()
    if existing:
        raise RuntimeError(
            f"charger_status_events holds {existing} rows carrying raw_payload, and this "
            "migration drops that column. Copy those payloads into poll_raw_payloads "
            "first - see PLAN 0.1. Refusing to discard captured data."
        )

    # --- (1) the lossless archive ------------------------------------------
    op.execute(
        """
        CREATE TABLE poll_raw_payloads (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
            observed_at  TIMESTAMPTZ NOT NULL,
            poll_run_id  UUID NOT NULL,
            source       VARCHAR(64) NOT NULL,
            page_no      INTEGER NOT NULL DEFAULT 0,
            raw_payload  JSONB,
            ingested_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (id, observed_at)
        ) PARTITION BY RANGE (observed_at)
        """
    )
    # Indexed for replay (by source, in order) and for joining a run to what
    # it captured. NOT indexed on raw_payload: nothing queries into it, and a
    # GIN index would cost more than the table.
    op.execute(
        "CREATE INDEX ix_prp_source_time ON poll_raw_payloads (source, observed_at, page_no)"
    )
    op.execute("CREATE INDEX ix_prp_run ON poll_raw_payloads (poll_run_id)")

    for statement in _partition_statements("poll_raw_payloads", MONTHS_AHEAD):
        conn.execute(sa.text(statement))
    op.execute("CREATE TABLE poll_raw_payloads_default PARTITION OF poll_raw_payloads DEFAULT")

    # Append-only in the database, not by convention (AGENTS.md constraint 3).
    # Rules are inherited by partitions. Note TRUNCATE is NOT covered by rules.
    op.execute(
        """
        CREATE RULE poll_raw_payloads_no_update AS
            ON UPDATE TO poll_raw_payloads DO INSTEAD NOTHING;
        CREATE RULE poll_raw_payloads_no_delete AS
            ON DELETE TO poll_raw_payloads DO INSTEAD NOTHING;
        """
    )

    # --- (2) the derived log ------------------------------------------------
    # Rules intercept DML, not DDL, so ALTER works on the append-only table.
    op.execute(
        "ALTER TABLE charger_status_events "
        "ADD COLUMN transition VARCHAR(16) NOT NULL DEFAULT 'changed'"
    )
    # Drop the default immediately: every writer states its own reason, and a
    # silent 'changed' would make a disappearance indistinguishable from a
    # source genuinely reporting a new status.
    op.execute("ALTER TABLE charger_status_events ALTER COLUMN transition DROP DEFAULT")
    op.execute("ALTER TABLE charger_status_events DROP COLUMN raw_payload")

    # --- the rebuildable cache ---------------------------------------------
    op.create_table(
        "connector_state",
        sa.Column("source", sa.String(64), primary_key=True),
        sa.Column("source_station_id", sa.String(255), primary_key=True),
        sa.Column("connector_id", sa.String(255), primary_key=True),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("last_status_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_connector_state_source_status", "connector_state", ["source", "status"])

    # --- the liveness ledger gains the counters the console needs ----------
    op.add_column(
        "poll_runs",
        sa.Column("raw_pages_written", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "poll_runs",
        sa.Column("connectors_seen", sa.Integer(), nullable=False, server_default="0"),
    )

    op.execute(
        """
        INSERT INTO schema_version (version, note)
        VALUES (4, 'PART 0.1 storage split: poll_raw_payloads (lossless) + '
                   'charger_status_events as derived transitions + connector_state cache')
        """
    )


def _partition_statements(table: str, months: int) -> list[str]:
    """Monthly partitions from the start of the current month.

    Generated in SQL from ``date_trunc(now())`` rather than from a Python
    date, so re-running this migration on a different day still produces a
    contiguous, gap-free set.
    """
    statements: list[str] = []
    for offset in range(months):
        statements.append(
            f"""
            DO $$
            DECLARE
                start_at DATE := (date_trunc('month', now()) + INTERVAL '{offset} month')::date;
                end_at   DATE := (date_trunc('month', now()) + INTERVAL '{offset + 1} month')::date;
                part     TEXT := '{table}_' || to_char(start_at, 'YYYY_MM');
            BEGIN
                EXECUTE format(
                    'CREATE TABLE IF NOT EXISTS %I PARTITION OF {table} '
                    'FOR VALUES FROM (%L) TO (%L)', part, start_at, end_at
                );
            END $$;
            """
        )
    return statements


def downgrade() -> None:
    op.drop_column("poll_runs", "connectors_seen")
    op.drop_column("poll_runs", "raw_pages_written")
    op.drop_index("ix_connector_state_source_status", table_name="connector_state")
    op.drop_table("connector_state")

    op.execute("ALTER TABLE charger_status_events ADD COLUMN raw_payload JSONB")
    op.execute("ALTER TABLE charger_status_events DROP COLUMN transition")

    op.execute("DROP RULE IF EXISTS poll_raw_payloads_no_update ON poll_raw_payloads")
    op.execute("DROP RULE IF EXISTS poll_raw_payloads_no_delete ON poll_raw_payloads")
    op.execute("DROP TABLE IF EXISTS poll_raw_payloads CASCADE")  # cascades to partitions

    op.execute("DELETE FROM schema_version WHERE version = 4")
